#-------------------- ItemCase Configuration File --------------------#
# This file contains all of the ItemCase configuration settings that  #
# can be altered.                                                     #
#---------------------------------------------------------------------#

# Locale: 
#     - EN
Locale: EN
   
# Materials that can be used for ItemCases.
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
Materials:
    - 'STEP'                # Slabs.
    - 'STONE_SLAB2'         # Red Sandstone Slabs.
    - 'WOOD_STEP'           # Wooden Slabs.
    - 'PURPUR_SLAB'         # Purpur Slabs.